/**
 * WebSocket Message Contracts
 * TypeScript type definitions for all WebSocket message types in the Nexus Backend API
 * 
 * @generated This file is auto-generated from websocket-contracts.json
 * Do not edit this file directly. Run 'npm run generate:ws-types' to regenerate.
 */

// ============================================================================
// Audio Types (Shared)
// ============================================================================

export type AudioFormat = 'pcm_16000' | 'pcm_22050' | 'pcm_44100'

// ============================================================================
// Authentication and Project Settings
// ============================================================================

export interface AuthRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for authentication
   */
  type: 'auth';
  /**
   * API key for authentication
   */
  apiKey: string;
}

export interface AuthResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for authentication response
   */
  type: 'auth';
  /**
   * Whether authentication was successful
   */
  success: boolean;
  /**
   * Unique identifier for the automatically created session
   */
  sessionId?: string;
  /**
   * Project settings available after authentication
   */
  projectSettings?: {
    /**
     * Unique identifier of the project
     */
    projectId: string;
    /**
     * Whether conversations can accept voice input
     */
    acceptVoice: boolean;
    /**
     * Whether conversations generate voice output
     */
    generateVoice: boolean;
    /**
     * ASR configuration settings with full ASR settings
     */
    asrConfig?: {
      /**
       * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
       */
      asrProviderId?: string;
      /**
       * ASR-specific settings including model, language preferences, etc.
       */
      settings?: {
        /**
         * The language code for speech recognition (e.g., "en-US")
         */
        language?: string;
        /**
         * The phrases to add to the speech recognition dictionary
         */
        dictionaryPhrases?: string[];
        /**
         * Audio input format for speech recognition (e.g., "pcm_16000")
         */
        audioFormat?: 'pcm_16000' | 'pcm_22050' | 'pcm_44100';
      };
      /**
       * Placeholder text to use when speech is unintelligible or cannot be transcribed
       */
      unintelligiblePlaceholder?: string;
      /**
       * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
       */
      voiceActivityDetection?: boolean;
    } | null;
  };
  /**
   * Error message if authentication failed
   */
  error?: string;
}

export interface ProjectSettings {
  /**
   * Unique identifier of the project
   */
  projectId: string;
  /**
   * Whether conversations can accept voice input
   */
  acceptVoice: boolean;
  /**
   * Whether conversations generate voice output
   */
  generateVoice: boolean;
  /**
   * ASR configuration settings with full ASR settings
   */
  asrConfig?: {
    /**
     * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
     */
    asrProviderId?: string;
    /**
     * ASR-specific settings including model, language preferences, etc.
     */
    settings?: {
      /**
       * The language code for speech recognition (e.g., "en-US")
       */
      language?: string;
      /**
       * The phrases to add to the speech recognition dictionary
       */
      dictionaryPhrases?: string[];
      /**
       * Audio input format for speech recognition (e.g., "pcm_16000")
       */
      audioFormat?: 'pcm_16000' | 'pcm_22050' | 'pcm_44100';
    };
    /**
     * Placeholder text to use when speech is unintelligible or cannot be transcribed
     */
    unintelligiblePlaceholder?: string;
    /**
     * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
     */
    voiceActivityDetection?: boolean;
  } | null;
}

// ============================================================================
// Session and Conversation Lifecycle
// ============================================================================

export interface StartConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for starting a new conversation
   */
  type: 'start_conversation';
  /**
   * Session ID in which to start the conversation
   */
  sessionId: string;
  /**
   * User ID initiating the conversation
   */
  userId: string;
  /**
   * Optional persona ID for the conversation
   */
  personaId?: string;
  /**
   * Stage ID to initiate the conversation at a specific stage
   */
  stageId: string;
}

export interface StartConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for start conversation response
   */
  type: 'start_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully started
   */
  success: boolean;
  /**
   * Unique identifier for the created conversation
   */
  conversationId?: string;
  /**
   * Error message if conversation creation failed
   */
  error?: string;
}

export interface ResumeConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for resuming a conversation
   */
  type: 'resume_conversation';
  /**
   * Session ID in which to resume the conversation
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation to resume
   */
  conversationId: string;
}

export interface ResumeConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for resume conversation response
   */
  type: 'resume_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully resumed
   */
  success: boolean;
  /**
   * Unique identifier of the resumed conversation
   */
  conversationId?: string;
  /**
   * Error message if conversation resumption failed
   */
  error?: string;
}

export interface EndConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for ending a conversation
   */
  type: 'end_conversation';
  /**
   * Session ID containing the conversation
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation to end
   */
  conversationId: string;
}

export interface EndConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for end conversation response
   */
  type: 'end_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully ended
   */
  success: boolean;
  /**
   * Error message if conversation termination failed
   */
  error?: string;
}

// ============================================================================
// User Input (Voice and Text)
// ============================================================================

export interface StartUserVoiceInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for starting user voice input
   */
  type: 'start_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
}

export interface StartUserVoiceInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for start user voice input response
   */
  type: 'start_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice input was successfully started
   */
  success: boolean;
  /**
   * Error message if voice input start failed
   */
  error?: string;
}

export interface SendUserVoiceChunkRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for sending user voice chunk
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
}

export interface SendUserVoiceChunkResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for send user voice chunk response
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice chunk was successfully received
   */
  success: boolean;
  /**
   * Error message if voice chunk processing failed
   */
  error?: string;
}

export interface EndUserVoiceInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for ending user voice input
   */
  type: 'end_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
}

export interface EndUserVoiceInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for end user voice input response
   */
  type: 'end_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice input was successfully ended
   */
  success: boolean;
  /**
   * Error message if voice input ending failed
   */
  error?: string;
}

export interface SendUserTextInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for sending user text input
   */
  type: 'send_user_text_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Text content from the user
   */
  text: string;
}

export interface SendUserTextInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for send user text input response
   */
  type: 'send_user_text_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether text input was successfully received
   */
  success: boolean;
  /**
   * Error message if text input processing failed
   */
  error?: string;
}

// ============================================================================
// AI Response (Voice Output)
// ============================================================================

export interface StartAiVoiceOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for starting AI voice output
   */
  type: 'start_ai_voice_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  voiceOutputId: string;
}

export interface SendAiVoiceChunk {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for sending AI voice chunk
   */
  type: 'send_ai_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  voiceOutputId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
  /**
   * Audio format of the chunk data
   */
  audioFormat: 'pcm_16000' | 'pcm_22050' | 'pcm_44100';
  /**
   * Unique identifier for this specific audio chunk
   */
  chunkId: string;
  /**
   * Sequential order of this chunk in the voice output sequence
   */
  ordinal: number;
  /**
   * Whether this is the final chunk in the voice output sequence
   */
  isFinal: boolean;
}

export interface EndAiVoiceOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for ending AI voice output
   */
  type: 'end_ai_voice_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  voiceOutputId: string;
  /**
   * The full text that was converted to speech, if available
   */
  fullText: string;
}

// ============================================================================
// Commands (Stage Navigation, Variables, Actions)
// ============================================================================

export interface GoToStageRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for navigating to a stage
   */
  type: 'go_to_stage';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the target stage
   */
  stageId: string;
}

export interface GoToStageResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for go to stage response
   */
  type: 'go_to_stage';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether navigation to the stage was successful
   */
  success: boolean;
  /**
   * Error message if navigation failed
   */
  error?: string;
}

export interface SetVarRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for setting a variable
   */
  type: 'set_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
  /**
   * Name of the variable to set
   */
  variableName: string;
  /**
   * Value to set for the variable (can be any JSON-serializable type)
   */
  variableValue: {
    [k: string]: unknown;
  };
}

export interface SetVarResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for set variable response
   */
  type: 'set_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variable was successfully set
   */
  success: boolean;
  /**
   * Error message if setting the variable failed
   */
  error?: string;
}

export interface GetVarRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for getting a variable
   */
  type: 'get_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
  /**
   * Name of the variable to retrieve
   */
  variableName: string;
}

export interface GetVarResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for get variable response
   */
  type: 'get_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variable was successfully retrieved
   */
  success: boolean;
  /**
   * Name of the retrieved variable
   */
  variableName: string;
  /**
   * Value of the variable (undefined if not found)
   */
  variableValue?: {
    [k: string]: unknown;
  };
  /**
   * Error message if retrieving the variable failed
   */
  error?: string;
}

export interface GetAllVarsRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for getting all variables
   */
  type: 'get_all_vars';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
}

export interface GetAllVarsResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for get all variables response
   */
  type: 'get_all_vars';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variables were successfully retrieved
   */
  success: boolean;
  /**
   * Map of variable names to their values
   */
  variables: {
    [k: string]: unknown;
  };
  /**
   * Error message if retrieving variables failed
   */
  error?: string;
}

export interface RunActionRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for running an action
   */
  type: 'run_action';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Name of the global action to execute
   */
  actionName: string;
  /**
   * Array of parameters to pass to the action
   */
  parameters: unknown[];
}

export interface RunActionResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for run action response
   */
  type: 'run_action';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the action was successfully executed
   */
  success: boolean;
  /**
   * Result returned by the action
   */
  result?: {
    [k: string]: unknown;
  };
  /**
   * Error message if action execution failed
   */
  error?: string;
}

