/**
 * WebSocket Message Contracts
 * TypeScript type definitions for all WebSocket message types in the Bonsai Backend API
 * 
 * @generated This file is auto-generated from websocket-contracts.json
 * Do not edit this file directly. Run 'npm run generate:ws-types' to regenerate.
 */

// ============================================================================
// Audio Types (Shared)
// ============================================================================

export type AudioFormat = 'mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm_8000' | 'pcm_16000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100' | 'pcm_48000' | 'mulaw' | 'alaw'
// ============================================================================
// Shared Types (Parameters)
// ============================================================================

/**
 * Image parameter value structure for multimodal parameters
 */
export interface ImageParameterValue {
  /**
   * Base64-encoded image data
   */
  data: string;
  /**
   * MIME type of the image (e.g., image/png, image/jpeg, image/webp)
   */
  mimeType: string;
  /**
   * Optional metadata about the image
   */
  metadata?: {
    /**
     * Image width in pixels
     */
    width?: number;
    /**
     * Image height in pixels
     */
    height?: number;

  };
}

/**
 * Audio parameter value structure for multimodal parameters
 */
export interface AudioParameterValue {
  /**
   * Base64-encoded audio data
   */
  data: string;
  /**
   * Audio format identifier (pcm, mp3, wav, opus)
   */
  format: 'pcm' | 'mp3' | 'wav' | 'opus';
  /**
   * MIME type of the audio (e.g., audio/pcm, audio/mpeg, audio/wav)
   */
  mimeType: string;
  /**
   * Optional metadata about the audio
   */
  metadata?: {
    /**
     * Sample rate in Hz (e.g., 44100, 48000)
     */
    sampleRate?: number;
    /**
     * Number of audio channels (1 for mono, 2 for stereo)
     */
    channels?: number;
    /**
     * Bit depth per sample (e.g., 16, 24)
     */
    bitDepth?: number;

  };
}

/**
 * Value of the parameter, can be a primitive type, an array of primitives, a free-form JSON object, or a multimodal parameter (image or audio)
 */
export type ParameterValue =
  | string
  | number
  | boolean
  | {

    }
  | string[]
  | number[]
  | boolean[]
  | {

    }[]
  | ImageParameterValue
  | AudioParameterValue;

/**
 * The effect to be executed
 */
export type Effect =
  | EndConversationEffect
  | AbortConversationEffect
  | GoToStageEffect
  | ModifyUserInputEffect
  | ModifyVariablesEffect
  | ModifyUserProfileEffect
  | CallToolEffect
  | GenerateResponseEffect
  | ChangeVisibilityEffect
  | BanUserEffect;

export interface EndConversationEffect {
  /**
   * Effect type
   */
  type: 'end_conversation';
  /**
   * Optional reason for ending the conversation
   */
  reason?: string;
}

export interface AbortConversationEffect {
  /**
   * Effect type
   */
  type: 'abort_conversation';
  /**
   * Optional reason for aborting the conversation
   */
  reason?: string;
}

export interface GoToStageEffect {
  /**
   * Effect type
   */
  type: 'go_to_stage';
  /**
   * ID of the stage to switch to
   */
  stageId: string;
}

export interface ModifyUserInputEffect {
  /**
   * Effect type
   */
  type: 'modify_user_input';
  /**
   * Template to render and replace user input with
   */
  template: string;
}

export interface ModifyVariablesEffect {
  /**
   * Effect type
   */
  type: 'modify_variables';
  /**
   * Array of variable modifications to apply
   *
   * @minItems 1
   */
  modifications: [VariableOperation, ...VariableOperation[]];
}

export interface VariableOperation {
  /**
   * Name of the variable to modify
   */
  variableName: string;
  /**
   * Operation to perform: set (assign value), reset (clear value), add (append to array), remove (remove from array)
   */
  operation: 'set' | 'reset' | 'add' | 'remove';
  /**
   * Value for the operation (not used for reset operation)
   */
  value?: {

  };
}

export interface ModifyUserProfileEffect {
  /**
   * Effect type
   */
  type: 'modify_user_profile';
  /**
   * Array of user profile field modifications to apply
   *
   * @minItems 1
   */
  modifications: [UserProfileOperation, ...UserProfileOperation[]];
}

export interface UserProfileOperation {
  /**
   * Name of the profile field to modify
   */
  fieldName: string;
  /**
   * Operation to perform: set (assign value), reset (clear value), add (append to array), remove (remove from array)
   */
  operation: 'set' | 'reset' | 'add' | 'remove';
  /**
   * Value for the operation (not used for reset operation)
   */
  value?: {

  };
}

export interface CallToolEffect {
  /**
   * Effect type
   */
  type: 'call_tool';
  /**
   * ID of the tool to call
   */
  toolId: string;
  /**
   * Parameters to pass to the tool
   */
  parameters: {

  };
}

export interface GenerateResponseEffect {
  /**
   * Effect type
   */
  type: 'generate_response';
  /**
   * Type of response to generate: generated (AI-generated), prescripted (predefined response), best_match (choose the best match from predefined responses)
   */
  responseMode?: 'generated' | 'prescripted';
  /**
   * Strategy to select prescripted response when multiple are provided
   */
  prescriptedSelectionStrategy?: 'random' | 'round_robin';
  /**
   * Optional array of prescripted responses to use
   */
  prescriptedResponses?: string[];
}

export interface ChangeVisibilityEffect {
  /**
   * Effect type
   */
  type: 'change_visibility';
  /**
   * Visibility setting: always (always visible), stage (visible only in current stage), never (never visible), conditional (visible based on a JavaScript condition expression)
   */
  visibility: 'always' | 'stage' | 'never' | 'conditional';
  /**
   * JavaScript condition expression evaluated against the conversation context — required when visibility is "conditional"
   */
  condition?: string;
}

export interface BanUserEffect {
  /**
   * Effect type
   */
  type: 'ban_user';
  /**
   * Optional reason for banning the user
   */
  reason?: string;
}

/**
 * Server-side VAD configuration. When set, the server autonomously detects speech boundaries — clients send continuous audio without calling start/end_user_voice_input.
 */
export interface ServerVadConfig {
  /**
   * VAD aggressiveness level (0–3). Higher values are more aggressive at filtering non-speech. Default: 2.
   */
  mode?: number;
  /**
   * Duration of each VAD processing frame in milliseconds. Must be 10, 20, or 30. Default: 20.
   */
  frameDurationMs?: 10 | 20 | 30;
  /**
   * Amount of silence (in ms) to prepend before the detected speech start as a pre-roll buffer. Default: 300.
   */
  silencePaddingMs?: number;
  /**
   * Duration of silence (in ms) after speech that triggers end-of-utterance detection. Default: 800.
   */
  autoEndSilenceDurationMs?: number;
}


// ============================================================================
// Authentication and Project Settings
// ============================================================================

export interface AuthRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for authentication
   */
  type: 'auth';
  /**
   * API key for authentication
   */
  apiKey: string;
  /**
   * Session settings for the client
   */
  sessionSettings?: {
    /**
     * Whether the client can send voice input
     */
    sendVoiceInput?: boolean;
    /**
     * Whether the client can send text input
     */
    sendTextInput?: boolean;
    /**
     * Whether the client wants to receive voice output
     */
    receiveVoiceOutput?: boolean;
    /**
     * Whether the client wants to receive intermediate transcription updates for voice input and output
     */
    receiveTranscriptionUpdates?: boolean;
    /**
     * Whether the client wants to receive all conversation events (e.g. turn start/end, agent actions)
     */
    receiveEvents?: boolean;
    /**
     * Audio format the client sends for voice input (e.g. pcm_16000, opus, mulaw). Defaults to pcm_16000.
     */
    sendAudioFormat?:
      | 'mp3'
      | 'opus'
      | 'aac'
      | 'flac'
      | 'wav'
      | 'pcm_8000'
      | 'pcm_16000'
      | 'pcm_22050'
      | 'pcm_24000'
      | 'pcm_44100'
      | 'pcm_48000'
      | 'mulaw'
      | 'alaw';
    /**
     * Preferred audio format for AI voice output. Omit to receive the provider native format without conversion. Defaults to pcm_16000.
     */
    receiveAudioFormat?:
      | 'mp3'
      | 'opus'
      | 'aac'
      | 'flac'
      | 'wav'
      | 'pcm_8000'
      | 'pcm_16000'
      | 'pcm_22050'
      | 'pcm_24000'
      | 'pcm_44100'
      | 'pcm_48000'
      | 'mulaw'
      | 'alaw';
  };
}

export interface AuthResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for authentication response
   */
  type: 'auth';
  /**
   * Whether authentication was successful
   */
  success: boolean;
  /**
   * Unique identifier for the automatically created session
   */
  sessionId?: string;
  /**
   * Project settings available after authentication
   */
  projectSettings?: {
    /**
     * Unique identifier of the project
     */
    projectId: string;
    /**
     * Whether conversations can accept voice input
     */
    acceptVoice: boolean;
    /**
     * Whether conversations generate voice output
     */
    generateVoice: boolean;
    /**
     * ASR configuration settings with full ASR settings
     */
    asrConfig?: {
      /**
       * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
       */
      asrProviderId?: string;
      /**
       * ASR-specific settings including model, language preferences, etc.
       */
      settings?:
        | AzureAsrSettings
        | ElevenLabsAsrSettings
        | DeepgramAsrSettings
        | AssemblyAiAsrSettings
        | SpeechmaticsAsrSettings;
      /**
       * Placeholder text to use when speech is unintelligible or cannot be transcribed
       */
      unintelligiblePlaceholder?: string;
      /**
       * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
       */
      voiceActivityDetection?: boolean;
      serverVad?: ServerVadConfig;
    };
  };
  /**
   * Error message if authentication failed
   */
  error?: string;
}

export interface ProjectSettings {
  /**
   * Unique identifier of the project
   */
  projectId: string;
  /**
   * Whether conversations can accept voice input
   */
  acceptVoice: boolean;
  /**
   * Whether conversations generate voice output
   */
  generateVoice: boolean;
  /**
   * ASR configuration settings with full ASR settings
   */
  asrConfig?: {
    /**
     * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
     */
    asrProviderId?: string;
    /**
     * ASR-specific settings including model, language preferences, etc.
     */
    settings?:
      | AzureAsrSettings
      | ElevenLabsAsrSettings
      | DeepgramAsrSettings
      | AssemblyAiAsrSettings
      | SpeechmaticsAsrSettings;
    /**
     * Placeholder text to use when speech is unintelligible or cannot be transcribed
     */
    unintelligiblePlaceholder?: string;
    /**
     * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
     */
    voiceActivityDetection?: boolean;
    serverVad?: ServerVadConfig;
  };
}

/**
 * Azure Speech Recognition settings
 */
export interface AzureAsrSettings {
  /**
   * The language code for speech recognition (e.g., 'en-US')
   */
  language?: string;
  /**
   * The phrases to add to the speech recognition dictionary
   */
  dictionaryPhrases?: string[];
  /**
   * Audio input format for speech recognition (e.g., "pcm_16000")
   */
  audioFormat?:
    | 'mp3'
    | 'opus'
    | 'aac'
    | 'flac'
    | 'wav'
    | 'pcm_8000'
    | 'pcm_16000'
    | 'pcm_22050'
    | 'pcm_24000'
    | 'pcm_44100'
    | 'pcm_48000'
    | 'mulaw'
    | 'alaw';

}

/**
 * ElevenLabs Scribe settings
 */
export interface ElevenLabsAsrSettings {
  /**
   * Model ID to use for transcription (e.g., "scribe_v2_realtime"), defaults to scribe_v2_realtime
   */
  modelId?: string;
  /**
   * Audio encoding format for speech-to-text, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100';
  /**
   * Language code in ISO 639-1 or ISO 639-3 format (e.g., "en", "es")
   */
  languageCode?: string;
  /**
   * Whether to receive word-level timestamps in transcription results, defaults to false
   */
  includeTimestamps?: boolean;
  /**
   * Whether to include detected language code in transcription results, defaults to false
   */
  includeLanguageDetection?: boolean;
  /**
   * Strategy for committing transcriptions - manual or voice activity detection, defaults to manual
   */
  commitStrategy?: 'manual' | 'vad';
  /**
   * Silence threshold in seconds for VAD (0.3-3), defaults to 1.5
   */
  vadSilenceThresholdSecs?: number;
  /**
   * Threshold for voice activity detection (0.1-0.9), defaults to 0.4
   */
  vadThreshold?: number;
  /**
   * Minimum speech duration in milliseconds (50-2000), defaults to 100
   */
  minSpeechDurationMs?: number;
  /**
   * Minimum silence duration in milliseconds (50-2000), defaults to 100
   */
  minSilenceDurationMs?: number;
  /**
   * When false, zero retention mode is used (enterprise only), defaults to true
   */
  enableLogging?: boolean;

}

/**
 * Deepgram speech-to-text settings
 */
export interface DeepgramAsrSettings {
  /**
   * Model ID to use for transcription (e.g., "nova-3", "nova-2", "base", "enhanced"), defaults to nova-3
   */
  modelId?: string;
  /**
   * Audio encoding format for speech-to-text, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100';
  /**
   * BCP-47 language tag (e.g., "en-US", "es", "fr")
   */
  language?: string;
  /**
   * Enable interim (partial) transcription results during streaming, defaults to false
   */
  interimResults?: boolean;
  /**
   * Milliseconds of silence to wait before finalizing speech (10+) or false to disable, defaults to 300
   */
  endpointing?: number | boolean;
  /**
   * Apply formatting (punctuation, capitalization, currency, etc.) to improve readability, defaults to true
   */
  smartFormat?: boolean;
  /**
   * Add punctuation and capitalization to transcript, defaults to true
   */
  punctuate?: boolean;
  /**
   * Recognize and label different speakers in the audio, defaults to false
   */
  diarize?: boolean;
  /**
   * Milliseconds to wait before sending UtteranceEnd event (use with interim_results)
   */
  utteranceEndMs?: number;
  /**
   * Send SpeechStarted events when speech is detected, defaults to false
   */
  vadEvents?: boolean;

}

/**
 * AssemblyAI speech-to-text settings
 */
export interface AssemblyAiAsrSettings {
  /**
   * Audio sample rate in Hz (8000, 16000, 22050, 24000, 44100), defaults to 16000
   */
  sampleRate?: number;
  /**
   * Enable formatted transcripts with capitalization and punctuation (adds latency, not recommended for voice agents), defaults to false
   */
  formatTurns?: boolean;
  /**
   * Speech model to use: English-only or multilingual (supports English, Spanish, French, German, Italian, Portuguese), defaults to universal-streaming-english
   */
  speechModel?: 'universal-streaming-english' | 'universal-streaming-multilingual';
  /**
   * List of custom words or phrases to improve recognition accuracy
   */
  keytermsPrompt?: string[];
  /**
   * Voice activity detection confidence threshold (0.0 to 1.0) for classifying audio frames as silence, defaults to 0.4
   */
  vadThreshold?: number;
  /**
   * Confidence threshold (0.0 to 1.0) for determining end of turn, defaults to 0.4
   */
  endOfTurnConfidenceThreshold?: number;
  /**
   * Minimum silence in milliseconds required to detect end of turn when confident, defaults to 400
   */
  minEndOfTurnSilenceWhenConfident?: number;
  /**
   * Maximum silence in milliseconds allowed in a turn before triggering end of turn, defaults to 1280
   */
  maxTurnSilence?: number;
  /**
   * Time in seconds of inactivity before session is terminated (5-3600), no timeout if not set
   */
  inactivityTimeout?: number;

}

/**
 * Speechmatics speech-to-text settings
 */
export interface SpeechmaticsAsrSettings {
  /**
   * Language code for speech recognition (e.g., "en", "en-US", "es", "fr")
   */
  language?: string;
  /**
   * Audio input format for speech recognition, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_44100';
  /**
   * Transcription mode: "standard" for faster processing or "enhanced" for higher accuracy, defaults to standard
   */
  transcriptionMode?: 'standard' | 'enhanced';
  /**
   * Enable automatic punctuation in transcripts, defaults to true
   */
  enablePunctuation?: boolean;
  /**
   * Enable automatic formatting (numbers, dates, currency, etc.), defaults to true
   */
  enableFormatting?: boolean;
  /**
   * Custom vocabulary words or phrases to improve recognition accuracy
   */
  additionalVocab?: string[];
  /**
   * Enable speaker diarization to detect different speakers, defaults to false
   */
  enableDiarization?: boolean;
  /**
   * Maximum delay in seconds for transcription results (0-10), lower values reduce latency
   */
  maxDelay?: number;

}


// ============================================================================
// Session and Conversation Lifecycle
// ============================================================================

export interface StartConversationRequest {
  type: 'start_conversation';
  /**
   * Identifier of the user initiating the conversation
   */
  userId: string;
  /**
   * Optional agent identifier to use for the conversation
   */
  agentId?: string;
  /**
   * Stage ID to initiate the conversation at a specific stage. When omitted, falls back to the project-level default starting stage.
   */
  stageId?: string;
  /**
   * IANA timezone identifier for this conversation (e.g. America/New_York, Europe/Warsaw). Overrides user profile and project timezone settings. Defaults to UTC when not provided by any source.
   */
  timezone?: string;
  /**
   * Direction of the conversation. Defaults to incoming when not specified.
   */
  direction?: 'incoming' | 'outgoing';
  /**
   * When set, the handler attaches to this pre-created conversation instead of creating a new one. Used for outgoing call flows where the conversation record is created at call initiation time.
   */
  existingConversationId?: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface StartConversationResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'start_conversation';
  /**
   * Whether conversation was successfully started
   */
  success: boolean;
  /**
   * Error message if conversation creation failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface ResumeConversationRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'resume_conversation';
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface ResumeConversationResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'resume_conversation';
  /**
   * Whether conversation was successfully resumed
   */
  success: boolean;
  /**
   * Error message if conversation resumption failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface EndConversationRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'end_conversation';
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface EndConversationResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'end_conversation';
  /**
   * Whether conversation was successfully ended
   */
  success: boolean;
  /**
   * Error message if conversation termination failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface ConversationEvent {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'conversation_event';
  /**
   * Identifier of the input turn associated with this event, when applicable
   */
  inputTurnId?: string;
  /**
   * Identifier of the output turn associated with this event, when applicable
   */
  outputTurnId?: string;
  /**
   * Type of the conversation event
   */
  eventType:
    | 'message'
    | 'classification'
    | 'transformation'
    | 'execution_plan'
    | 'action'
    | 'command'
    | 'tool_call'
    | 'conversation_start'
    | 'conversation_resume'
    | 'conversation_end'
    | 'conversation_aborted'
    | 'conversation_failed'
    | 'jump_to_stage'
    | 'moderation'
    | 'variables_updated'
    | 'user_profile_updated'
    | 'user_input_modified'
    | 'user_banned'
    | 'visibility_changed'
    | 'sample_copy_selection';
  /**
   * Data associated with the conversation event
   */
  eventData:
    | {
        role: 'user' | 'assistant';
        text: string;
        originalText: string;
        visibility?: {
          /**
           * Visibility setting for the message: always (always visible), stage (visible only in current stage), never (never visible), conditional (visible based on condition)
           */
          visibility: 'always' | 'stage' | 'never' | 'conditional';
          /**
           * Condition for visibility, evaluated against conversation variables
           */
          condition?: string;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        classifierId: string;
        input: string;
        actions: {
          classifierId: string;
          classifierName: string;
          actions: {
            name: string;
            parameters: {
              [k: string]: ParameterValue;
            };
          }[];
        }[];
        metadata?: Record<string, unknown>;
      }
    | {
        transformerId: string;
        input: string;
        appliedFields: string[];
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * ID of the stage where execution is taking place
         */
        stageId: string;
        /**
         * Names of all matched actions in original order
         */
        actions: string[];
        /**
         * Final ordered list of effects after filtering, sorting, and conflict resolution
         */
        effects: {
          /**
           * Name of the action this effect originates from
           */
          actionName: string;
          effect: Effect;
        }[];
        /**
         * Lifecycle context in which execution is taking place; null for user-input-triggered executions
         */
        lifecycleContext:
          | 'on_enter'
          | 'on_leave'
          | 'on_fallback'
          | 'conversation_start'
          | 'conversation_resume'
          | 'conversation_end'
          | 'conversation_abort'
          | 'conversation_failed'
          | null;
        metadata?: Record<string, unknown>;
      }
    | {
        actionName: string;
        stageId: string;
        effects: Effect[];
        metadata?: Record<string, unknown>;
      }
    | {
        command: 'go_to_stage' | 'set_var' | 'get_var' | 'get_all_vars' | 'run_action' | 'call_tool';
        parameters?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        toolId: string;
        toolName: string;
        toolType?: 'smart_function' | 'webhook' | 'script';
        parameters: {
          [k: string]: ParameterValue;
        };
        success: boolean;
        result?: {

        };
        error?: string;
        /**
         * Name of the action that triggered this tool call, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        stageId: string;
        initialVariables?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        previousStatus:
          | 'initialized'
          | 'awaiting_user_input'
          | 'receiving_user_voice'
          | 'processing_user_input'
          | 'generating_response'
          | 'finished'
          | 'aborted'
          | 'failed';
        stageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason?: string;
        stageId: string;
        /**
         * Name of the action that triggered conversation end, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId: string;
        /**
         * Name of the action that triggered conversation abort, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        fromStageId: string;
        toStageId: string;
        /**
         * Name of the action that triggered this stage jump, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        input: string;
        flagged: boolean;
        blockingCategories: string[];
        detectedCategories: string[];
        durationMs: number;
        startMs: number;
        endMs: number;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this variable update
         */
        sourceActionName: string;
        /**
         * Names of the variables that were changed by this update
         */
        changedVariableNames: string[];
        /**
         * Snapshot of all conversation variables after the update
         */
        variables: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this profile update
         */
        sourceActionName: string;
        /**
         * Names of the profile fields that were changed by this update
         */
        changedProfileNames: string[];
        /**
         * Updated user profile data
         */
        profile: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this input modification
         */
        sourceActionName: string;
        /**
         * The modified user input after template rendering
         */
        modifiedInput: string;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered the ban
         */
        sourceActionName: string;
        /**
         * Optional reason for the ban
         */
        reason?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this visibility change
         */
        sourceActionName: string;
        /**
         * The new visibility settings for current turn messages
         */
        visibility: {
          /**
           * Visibility setting for the message: always (always visible), stage (visible only in current stage), never (never visible), conditional (visible based on condition)
           */
          visibility: 'always' | 'stage' | 'never' | 'conditional';
          /**
           * Condition for visibility, evaluated against conversation variables
           */
          condition?: string;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * ID of the classifier that performed the selection
         */
        classifierId: string;
        /**
         * The user input that triggered the selection
         */
        input: string;
        /**
         * Identifier of selected sample copy, or null if none was selected
         */
        sampleCopy: string;
        metadata?: Record<string, unknown>;
      };
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface ConversationEventUpdate {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'conversation_event_update';
  /**
   * Identifier of the input turn associated with this event, when applicable
   */
  inputTurnId?: string;
  /**
   * Identifier of the output turn associated with this event, when applicable
   */
  outputTurnId?: string;
  /**
   * Type of the conversation event
   */
  eventType:
    | 'message'
    | 'classification'
    | 'transformation'
    | 'execution_plan'
    | 'action'
    | 'command'
    | 'tool_call'
    | 'conversation_start'
    | 'conversation_resume'
    | 'conversation_end'
    | 'conversation_aborted'
    | 'conversation_failed'
    | 'jump_to_stage'
    | 'moderation'
    | 'variables_updated'
    | 'user_profile_updated'
    | 'user_input_modified'
    | 'user_banned'
    | 'visibility_changed'
    | 'sample_copy_selection';
  /**
   * Updated data for the conversation event
   */
  eventData:
    | {
        role: 'user' | 'assistant';
        text: string;
        originalText: string;
        visibility?: {
          /**
           * Visibility setting for the message: always (always visible), stage (visible only in current stage), never (never visible), conditional (visible based on condition)
           */
          visibility: 'always' | 'stage' | 'never' | 'conditional';
          /**
           * Condition for visibility, evaluated against conversation variables
           */
          condition?: string;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        classifierId: string;
        input: string;
        actions: {
          classifierId: string;
          classifierName: string;
          actions: {
            name: string;
            parameters: {
              [k: string]: ParameterValue;
            };
          }[];
        }[];
        metadata?: Record<string, unknown>;
      }
    | {
        transformerId: string;
        input: string;
        appliedFields: string[];
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * ID of the stage where execution is taking place
         */
        stageId: string;
        /**
         * Names of all matched actions in original order
         */
        actions: string[];
        /**
         * Final ordered list of effects after filtering, sorting, and conflict resolution
         */
        effects: {
          /**
           * Name of the action this effect originates from
           */
          actionName: string;
          effect: Effect;
        }[];
        /**
         * Lifecycle context in which execution is taking place; null for user-input-triggered executions
         */
        lifecycleContext:
          | 'on_enter'
          | 'on_leave'
          | 'on_fallback'
          | 'conversation_start'
          | 'conversation_resume'
          | 'conversation_end'
          | 'conversation_abort'
          | 'conversation_failed'
          | null;
        metadata?: Record<string, unknown>;
      }
    | {
        actionName: string;
        stageId: string;
        effects: Effect[];
        metadata?: Record<string, unknown>;
      }
    | {
        command: 'go_to_stage' | 'set_var' | 'get_var' | 'get_all_vars' | 'run_action' | 'call_tool';
        parameters?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        toolId: string;
        toolName: string;
        toolType?: 'smart_function' | 'webhook' | 'script';
        parameters: {
          [k: string]: ParameterValue;
        };
        success: boolean;
        result?: {

        };
        error?: string;
        /**
         * Name of the action that triggered this tool call, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        stageId: string;
        initialVariables?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        previousStatus:
          | 'initialized'
          | 'awaiting_user_input'
          | 'receiving_user_voice'
          | 'processing_user_input'
          | 'generating_response'
          | 'finished'
          | 'aborted'
          | 'failed';
        stageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason?: string;
        stageId: string;
        /**
         * Name of the action that triggered conversation end, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId: string;
        /**
         * Name of the action that triggered conversation abort, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        fromStageId: string;
        toStageId: string;
        /**
         * Name of the action that triggered this stage jump, if triggered by an action effect
         */
        sourceActionName?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        input: string;
        flagged: boolean;
        blockingCategories: string[];
        detectedCategories: string[];
        durationMs: number;
        startMs: number;
        endMs: number;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this variable update
         */
        sourceActionName: string;
        /**
         * Names of the variables that were changed by this update
         */
        changedVariableNames: string[];
        /**
         * Snapshot of all conversation variables after the update
         */
        variables: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this profile update
         */
        sourceActionName: string;
        /**
         * Names of the profile fields that were changed by this update
         */
        changedProfileNames: string[];
        /**
         * Updated user profile data
         */
        profile: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this input modification
         */
        sourceActionName: string;
        /**
         * The modified user input after template rendering
         */
        modifiedInput: string;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered the ban
         */
        sourceActionName: string;
        /**
         * Optional reason for the ban
         */
        reason?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * Name of the action that triggered this visibility change
         */
        sourceActionName: string;
        /**
         * The new visibility settings for current turn messages
         */
        visibility: {
          /**
           * Visibility setting for the message: always (always visible), stage (visible only in current stage), never (never visible), conditional (visible based on condition)
           */
          visibility: 'always' | 'stage' | 'never' | 'conditional';
          /**
           * Condition for visibility, evaluated against conversation variables
           */
          condition?: string;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        /**
         * ID of the classifier that performed the selection
         */
        classifierId: string;
        /**
         * The user input that triggered the selection
         */
        input: string;
        /**
         * Identifier of selected sample copy, or null if none was selected
         */
        sampleCopy: string;
        metadata?: Record<string, unknown>;
      };
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}


// ============================================================================
// User Input (Voice and Text)
// ============================================================================

export interface StartUserVoiceInputRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'start_user_voice_input';
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface StartUserVoiceInputResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'start_user_voice_input';
  /**
   * Whether voice input was successfully started
   */
  success: boolean;
  /**
   * Identifier for the new voice input turn. Present when success is true
   */
  inputTurnId?: string;
  /**
   * Error message if voice input start failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendUserVoiceChunkRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for sending user voice chunk
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
  /**
   * Sequential order of this chunk in the voice input sequence
   */
  ordinal: number;
  /**
   * Unique identifier for the input turn. Optional in server VAD mode where the turn ID is managed server-side.
   */
  inputTurnId?: string;
}

export interface SendUserVoiceChunkResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for send user voice chunk response
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice chunk was successfully received
   */
  success: boolean;
  /**
   * Error message if voice chunk processing failed
   */
  error?: string;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId?: string;
}

export interface EndUserVoiceInputRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'end_user_voice_input';
  /**
   * Identifier of the input turn to close, as returned by the corresponding result message
   */
  inputTurnId: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface EndUserVoiceInputResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'end_user_voice_input';
  /**
   * Whether voice input was successfully ended
   */
  success: boolean;
  /**
   * Identifier of the voice input turn that was closed
   */
  inputTurnId: string;
  /**
   * Error message if voice input ending failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendUserTextInputRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'send_user_text_input';
  /**
   * Text content submitted by the user
   */
  text: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendUserTextInputResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'send_user_text_input';
  /**
   * Whether text input was successfully received
   */
  success: boolean;
  /**
   * Identifier of the input turn created for this text submission, can be used to correlate with conversation events
   */
  inputTurnId: string;
  /**
   * Error message if text input processing failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface UserTranscribedChunk {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'user_transcribed_chunk';
  /**
   * Input turn this transcription chunk belongs to
   */
  inputTurnId: string;
  /**
   * Unique identifier for this chunk
   */
  chunkId: string;
  /**
   * Transcribed text content
   */
  chunkText: string;
  /**
   * Sequential 0-based position within the transcription stream
   */
  ordinal: number;
  /**
   * True once ASR has finalised its transcript for this chunk
   */
  isFinal: boolean;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}


// ============================================================================
// AI Response (Voice Output)
// ============================================================================

export interface StartAiGenerationOutput {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'start_ai_generation_output';
  /**
   * Unique identifier for this generation turn; used to correlate all subsequent output messages
   */
  outputTurnId: string;
  /**
   * Whether the response will include synthesised voice audio
   */
  expectVoice: boolean;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendAiVoiceChunk {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'send_ai_voice_chunk';
  /**
   * Generation turn this chunk belongs to
   */
  outputTurnId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
  /**
   * Encoding of audioData
   */
  audioFormat:
    | 'mp3'
    | 'opus'
    | 'aac'
    | 'flac'
    | 'wav'
    | 'pcm_8000'
    | 'pcm_16000'
    | 'pcm_22050'
    | 'pcm_24000'
    | 'pcm_44100'
    | 'pcm_48000'
    | 'mulaw'
    | 'alaw';
  /**
   * Unique identifier for this specific chunk
   */
  chunkId: string;
  /**
   * Sequential 0-based position within the output turn's audio stream
   */
  ordinal: number;
  /**
   * Whether this is the final audio chunk for this output turn
   */
  isFinal: boolean;
  /**
   * Sample rate in Hz (e.g. 24000)
   */
  sampleRate?: number;
  /**
   * Bit rate in bits per second (e.g. 64000)
   */
  bitRate?: number;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface EndAiGenerationOutput {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'end_ai_generation_output';
  /**
   * Generation turn that has ended
   */
  outputTurnId: string;
  /**
   * Full text that was synthesised to speech (or generated, when voice is disabled)
   */
  fullText: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface AiTranscribedChunk {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'ai_transcribed_chunk';
  /**
   * Generation turn this chunk belongs to
   */
  outputTurnId: string;
  /**
   * Unique identifier for this chunk
   */
  chunkId: string;
  /**
   * Transcribed text content
   */
  chunkText: string;
  /**
   * Sequential 0-based position within the transcription stream
   */
  ordinal: number;
  /**
   * Whether this is the final transcription chunk for this output turn
   */
  isFinal: boolean;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendAiAudioOutput {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'send_ai_audio_output';
  /**
   * Generation turn this audio belongs to
   */
  outputTurnId: string;
  /**
   * Base64-encoded audio data
   */
  audioData: string;
  /**
   * Encoding of audioData
   */
  audioFormat:
    | 'mp3'
    | 'opus'
    | 'aac'
    | 'flac'
    | 'wav'
    | 'pcm_8000'
    | 'pcm_16000'
    | 'pcm_22050'
    | 'pcm_24000'
    | 'pcm_44100'
    | 'pcm_48000'
    | 'mulaw'
    | 'alaw';
  /**
   * MIME type of audioData (e.g. audio/mpeg, audio/wav)
   */
  mimeType: string;
  /**
   * 0-based index when multiple audio blocks are produced in a single response
   */
  sequenceNumber: number;
  /**
   * Optional low-level audio metadata
   */
  metadata?: {
    /**
     * Sample rate in Hz
     */
    sampleRate?: number;
    /**
     * Number of audio channels
     */
    channels?: number;
    /**
     * Bit depth per sample
     */
    bitDepth?: number;
  };
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SendAiImageOutput {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'send_ai_image_output';
  /**
   * Generation turn this image belongs to
   */
  outputTurnId: string;
  /**
   * Base64-encoded image data
   */
  imageData: string;
  /**
   * MIME type of imageData (e.g. image/png, image/jpeg)
   */
  mimeType: string;
  /**
   * 0-based index when multiple images are produced in a single response
   */
  sequenceNumber: number;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}


// ============================================================================
// Commands (Stage Navigation, Variables, Actions)
// ============================================================================

export interface GoToStageRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'go_to_stage';
  /**
   * Identifier of the target stage
   */
  stageId: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface GoToStageResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'go_to_stage';
  /**
   * Whether navigation to the stage was successful
   */
  success: boolean;
  /**
   * Error message if navigation failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SetVarRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'set_var';
  /**
   * Identifier of the stage that owns the variable
   */
  stageId: string;
  /**
   * Name of the variable to set
   */
  variableName: string;
  variableValue: ParameterValue & {

  };
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface SetVarResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'set_var_result';
  /**
   * Whether the variable was successfully set
   */
  success: boolean;
  /**
   * Error message if setting the variable failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface GetVarRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'get_var';
  /**
   * Identifier of the stage that owns the variable
   */
  stageId: string;
  /**
   * Name of the variable to retrieve
   */
  variableName: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface GetVarResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'get_var';
  /**
   * Whether the variable was successfully retrieved
   */
  success: boolean;
  /**
   * Name of the retrieved variable
   */
  variableName: string;
  /**
   * Value of the variable (absent when not found or success is false)
   */
  variableValue?:
    | string
    | number
    | boolean
    | {

      }
    | string[]
    | number[]
    | boolean[]
    | {

      }[]
    | ImageParameterValue
    | AudioParameterValue;
  /**
   * Error message if retrieving the variable failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface GetAllVarsRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'get_all_vars';
  /**
   * Identifier of the stage whose variables should be retrieved
   */
  stageId: string;
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface GetAllVarsResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'get_all_vars';
  /**
   * Whether the variables were successfully retrieved
   */
  success: boolean;
  /**
   * Map of variable names to their values
   */
  variables: {
    [k: string]: ParameterValue;
  };
  /**
   * Error message if retrieving variables failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface RunActionRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'run_action';
  /**
   * Name of the global action to execute
   */
  actionName: string;
  /**
   * Map of parameter names to their values
   */
  parameters: {
    [k: string]: ParameterValue;
  };
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface RunActionResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'run_action';
  /**
   * Whether the action was successfully executed
   */
  success: boolean;
  /**
   * Result returned by the action as array of multi-modal content blocks (text, image, or audio)
   */
  result?: (
    | {
        contentType: 'text';
        text: string;
      }
    | {
        contentType: 'image';
        /**
         * Base64-encoded image data
         */
        data: string;
        /**
         * MIME type (e.g., image/png, image/jpeg)
         */
        mimeType: string;
        metadata?: {
          width?: number;
          height?: number;

        };
      }
    | {
        contentType: 'audio';
        /**
         * Base64-encoded audio data
         */
        data: string;
        /**
         * Audio format
         */
        format: 'pcm' | 'mp3' | 'wav' | 'opus';
        /**
         * MIME type (e.g., audio/pcm, audio/mpeg)
         */
        mimeType: string;
        metadata?: {
          sampleRate?: number;
          channels?: number;
          bitDepth?: number;

        };
      }
  )[];
  /**
   * Error message if action execution failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface CallToolRequest {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'call_tool';
  /**
   * Unique identifier of the tool to execute
   */
  toolId: string;
  /**
   * Map of parameter names to their values
   */
  parameters: {
    [k: string]: ParameterValue;
  };
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

export interface CallToolResponse {
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  type: 'call_tool';
  /**
   * Whether the tool was successfully executed
   */
  success: boolean;
  /**
   * Result returned by the tool execution as array of multi-modal content blocks (text, image, or audio)
   */
  result?: (
    | {
        contentType: 'text';
        text: string;
      }
    | {
        contentType: 'image';
        /**
         * Base64-encoded image data
         */
        data: string;
        /**
         * MIME type (e.g., image/png, image/jpeg)
         */
        mimeType: string;
        metadata?: {
          width?: number;
          height?: number;

        };
      }
    | {
        contentType: 'audio';
        /**
         * Base64-encoded audio data
         */
        data: string;
        /**
         * Audio format
         */
        format: 'pcm' | 'mp3' | 'wav' | 'opus';
        /**
         * MIME type (e.g., audio/pcm, audio/mpeg)
         */
        mimeType: string;
        metadata?: {
          sampleRate?: number;
          channels?: number;
          bitDepth?: number;

        };
      }
  )[];
  /**
   * Error message if tool execution failed
   */
  error?: string;
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Unique identifier for the session
   */
  sessionId: string;
}

