/**
 * WebSocket Message Contracts
 * TypeScript type definitions for all WebSocket message types in the Bonsai Backend API
 * 
 * @generated This file is auto-generated from websocket-contracts.json
 * Do not edit this file directly. Run 'npm run generate:ws-types' to regenerate.
 */

// ============================================================================
// Audio Types (Shared)
// ============================================================================

export type AudioFormat = 'mp3' | 'opus' | 'aac' | 'flac' | 'wav' | 'pcm_8000' | 'pcm_16000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100' | 'pcm_48000' | 'mulaw' | 'alaw' | 'linear16'
// ============================================================================
// Shared Types (Parameters)
// ============================================================================

/**
 * Image parameter value structure for multimodal parameters
 */
export interface ImageParameterValue {
  /**
   * Base64-encoded image data
   */
  data: string;
  /**
   * MIME type of the image (e.g., image/png, image/jpeg, image/webp)
   */
  mimeType: string;
  /**
   * Optional metadata about the image
   */
  metadata?: {
    /**
     * Image width in pixels
     */
    width?: number;
    /**
     * Image height in pixels
     */
    height?: number;

  };
}

/**
 * Audio parameter value structure for multimodal parameters
 */
export interface AudioParameterValue {
  /**
   * Base64-encoded audio data
   */
  data: string;
  /**
   * Audio format identifier (pcm, mp3, wav, opus)
   */
  format: 'pcm' | 'mp3' | 'wav' | 'opus';
  /**
   * MIME type of the audio (e.g., audio/pcm, audio/mpeg, audio/wav)
   */
  mimeType: string;
  /**
   * Optional metadata about the audio
   */
  metadata?: {
    /**
     * Sample rate in Hz (e.g., 44100, 48000)
     */
    sampleRate?: number;
    /**
     * Number of audio channels (1 for mono, 2 for stereo)
     */
    channels?: number;
    /**
     * Bit depth per sample (e.g., 16, 24)
     */
    bitDepth?: number;

  };
}

/**
 * Value of the parameter, can be a primitive type, an array of primitives, a free-form JSON object, or a multimodal parameter (image or audio)
 */
export type ParameterValue =
  | string
  | number
  | boolean
  | {

    }
  | string[]
  | number[]
  | boolean[]
  | {

    }[]
  | ImageParameterValue
  | AudioParameterValue;

export type Effect =
  | EndConversationEffect
  | AbortConversationEffect
  | GoToStageEffect
  | RunScriptEffect
  | ModifyUserInputEffect
  | ModifyVariablesEffect
  | ModifyUserProfileEffect
  | CallToolEffect
  | CallWebhookEffect
  | GenerateResponseEffect;

export interface EndConversationEffect {
  /**
   * Effect type
   */
  type: 'end_conversation';
  /**
   * Optional reason for ending the conversation
   */
  reason?: string;
}

export interface AbortConversationEffect {
  /**
   * Effect type
   */
  type: 'abort_conversation';
  /**
   * Optional reason for aborting the conversation
   */
  reason?: string;
}

export interface GoToStageEffect {
  /**
   * Effect type
   */
  type: 'go_to_stage';
  /**
   * ID of the stage to switch to
   */
  stageId: string;
}

export interface RunScriptEffect {
  /**
   * Effect type
   */
  type: 'run_script';
  /**
   * JavaScript code to execute in isolated context
   */
  code: string;
}

export interface ModifyUserInputEffect {
  /**
   * Effect type
   */
  type: 'modify_user_input';
  /**
   * Template to render and replace user input with
   */
  template: string;
}

export interface ModifyVariablesEffect {
  /**
   * Effect type
   */
  type: 'modify_variables';
  /**
   * Array of variable modifications to apply
   *
   * @minItems 1
   */
  modifications: [VariableOperation, ...VariableOperation[]];
}

export interface VariableOperation {
  /**
   * Name of the variable to modify
   */
  variableName: string;
  /**
   * Operation to perform: set (assign value), reset (clear value), add (append to array), remove (remove from array)
   */
  operation: 'set' | 'reset' | 'add' | 'remove';
  /**
   * Value for the operation (not used for reset operation)
   */
  value?: {

  };
}

export interface ModifyUserProfileEffect {
  /**
   * Effect type
   */
  type: 'modify_user_profile';
  /**
   * Array of user profile field modifications to apply
   *
   * @minItems 1
   */
  modifications: [UserProfileOperation, ...UserProfileOperation[]];
}

export interface UserProfileOperation {
  /**
   * Name of the profile field to modify
   */
  fieldName: string;
  /**
   * Operation to perform: set (assign value), reset (clear value), add (append to array), remove (remove from array)
   */
  operation: 'set' | 'reset' | 'add' | 'remove';
  /**
   * Value for the operation (not used for reset operation)
   */
  value?: {

  };
}

export interface CallToolEffect {
  /**
   * Effect type
   */
  type: 'call_tool';
  /**
   * ID of the tool to call
   */
  toolId: string;
  /**
   * Parameters to pass to the tool
   */
  parameters: {

  };
}

export interface CallWebhookEffect {
  /**
   * Effect type
   */
  type: 'call_webhook';
  /**
   * HTTP(S) URL to call
   */
  url: string;
  /**
   * HTTP method to use
   */
  method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /**
   * HTTP headers to send with the request
   */
  headers?: {
    [k: string]: string;
  };
  /**
   * Request body for POST/PUT/PATCH requests
   */
  body?: {

  };
  /**
   * Key name to store the webhook result under in context.results.webhooks
   */
  resultKey: string;
}

export interface GenerateResponseEffect {
  /**
   * Effect type
   */
  type: 'generate_response';
  /**
   * Type of response to generate: generated (AI-generated), prescripted (predefined response), best_match (choose the best match from predefined responses)
   */
  responseMode?: 'generated' | 'prescripted';
  /**
   * Strategy to select prescripted response when multiple are provided
   */
  prescriptedSelectionStrategy?: 'random' | 'round_robin';
  /**
   * Optional array of prescripted responses to use
   */
  prescriptedResponses?: string[];
}


// ============================================================================
// Authentication and Project Settings
// ============================================================================

export interface AuthRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for authentication
   */
  type: 'auth';
  /**
   * API key for authentication
   */
  apiKey: string;
  /**
   * Session settings for the client
   */
  sessionSettings?: {
    /**
     * Whether the client can send voice input
     */
    sendVoiceInput?: boolean;
    /**
     * Whether the client can send text input
     */
    sendTextInput?: boolean;
    /**
     * Whether the client wants to receive voice output
     */
    receiveVoiceOutput?: boolean;
    /**
     * Whether the client wants to receive intermediate transcription updates for voice input and output
     */
    receiveTranscriptionUpdates?: boolean;
    /**
     * Whether the client wants to receive all conversation events (e.g. turn start/end, agent actions)
     */
    receiveEvents?: boolean;
  };
}

export interface AuthResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for authentication response
   */
  type: 'auth';
  /**
   * Whether authentication was successful
   */
  success: boolean;
  /**
   * Unique identifier for the automatically created session
   */
  sessionId?: string;
  /**
   * Project settings available after authentication
   */
  projectSettings?: {
    /**
     * Unique identifier of the project
     */
    projectId: string;
    /**
     * Whether conversations can accept voice input
     */
    acceptVoice: boolean;
    /**
     * Whether conversations generate voice output
     */
    generateVoice: boolean;
    /**
     * ASR configuration settings with full ASR settings
     */
    asrConfig?: {
      /**
       * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
       */
      asrProviderId?: string;
      /**
       * ASR-specific settings including model, language preferences, etc.
       */
      settings?:
        | AzureAsrSettings
        | ElevenLabsAsrSettings
        | DeepgramAsrSettings
        | AssemblyAiAsrSettings
        | SpeechmaticsAsrSettings;
      /**
       * Placeholder text to use when speech is unintelligible or cannot be transcribed
       */
      unintelligiblePlaceholder?: string;
      /**
       * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
       */
      voiceActivityDetection?: boolean;
    };
  };
  /**
   * Error message if authentication failed
   */
  error?: string;
}

export interface ProjectSettings {
  /**
   * Unique identifier of the project
   */
  projectId: string;
  /**
   * Whether conversations can accept voice input
   */
  acceptVoice: boolean;
  /**
   * Whether conversations generate voice output
   */
  generateVoice: boolean;
  /**
   * ASR configuration settings with full ASR settings
   */
  asrConfig?: {
    /**
     * ID of the ASR provider (e.g., "azure-speech", "openai-whisper")
     */
    asrProviderId?: string;
    /**
     * ASR-specific settings including model, language preferences, etc.
     */
    settings?:
      | AzureAsrSettings
      | ElevenLabsAsrSettings
      | DeepgramAsrSettings
      | AssemblyAiAsrSettings
      | SpeechmaticsAsrSettings;
    /**
     * Placeholder text to use when speech is unintelligible or cannot be transcribed
     */
    unintelligiblePlaceholder?: string;
    /**
     * Whether to enable voice activity detection to automatically start/stop recording based on speech presence
     */
    voiceActivityDetection?: boolean;
  };
}

/**
 * Azure Speech Recognition settings
 */
export interface AzureAsrSettings {
  /**
   * The language code for speech recognition (e.g., 'en-US')
   */
  language?: string;
  /**
   * The phrases to add to the speech recognition dictionary
   */
  dictionaryPhrases?: string[];
  /**
   * Audio input format for speech recognition (e.g., "pcm_16000")
   */
  audioFormat?:
    | 'mp3'
    | 'opus'
    | 'aac'
    | 'flac'
    | 'wav'
    | 'pcm_8000'
    | 'pcm_16000'
    | 'pcm_22050'
    | 'pcm_24000'
    | 'pcm_44100'
    | 'pcm_48000'
    | 'mulaw'
    | 'alaw'
    | 'linear16';

}

/**
 * ElevenLabs Scribe settings
 */
export interface ElevenLabsAsrSettings {
  /**
   * Model ID to use for transcription (e.g., "scribe_v2_realtime"), defaults to scribe_v2_realtime
   */
  modelId?: string;
  /**
   * Audio encoding format for speech-to-text, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100';
  /**
   * Language code in ISO 639-1 or ISO 639-3 format (e.g., "en", "es")
   */
  languageCode?: string;
  /**
   * Whether to receive word-level timestamps in transcription results, defaults to false
   */
  includeTimestamps?: boolean;
  /**
   * Whether to include detected language code in transcription results, defaults to false
   */
  includeLanguageDetection?: boolean;
  /**
   * Strategy for committing transcriptions - manual or voice activity detection, defaults to manual
   */
  commitStrategy?: 'manual' | 'vad';
  /**
   * Silence threshold in seconds for VAD (0.3-3), defaults to 1.5
   */
  vadSilenceThresholdSecs?: number;
  /**
   * Threshold for voice activity detection (0.1-0.9), defaults to 0.4
   */
  vadThreshold?: number;
  /**
   * Minimum speech duration in milliseconds (50-2000), defaults to 100
   */
  minSpeechDurationMs?: number;
  /**
   * Minimum silence duration in milliseconds (50-2000), defaults to 100
   */
  minSilenceDurationMs?: number;
  /**
   * When false, zero retention mode is used (enterprise only), defaults to true
   */
  enableLogging?: boolean;

}

/**
 * Deepgram speech-to-text settings
 */
export interface DeepgramAsrSettings {
  /**
   * Model ID to use for transcription (e.g., "nova-3", "nova-2", "base", "enhanced"), defaults to nova-3
   */
  modelId?: string;
  /**
   * Audio encoding format for speech-to-text, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_22050' | 'pcm_24000' | 'pcm_44100';
  /**
   * BCP-47 language tag (e.g., "en-US", "es", "fr")
   */
  language?: string;
  /**
   * Enable interim (partial) transcription results during streaming, defaults to false
   */
  interimResults?: boolean;
  /**
   * Milliseconds of silence to wait before finalizing speech (10+) or false to disable, defaults to 300
   */
  endpointing?: number | boolean;
  /**
   * Apply formatting (punctuation, capitalization, currency, etc.) to improve readability, defaults to true
   */
  smartFormat?: boolean;
  /**
   * Add punctuation and capitalization to transcript, defaults to true
   */
  punctuate?: boolean;
  /**
   * Recognize and label different speakers in the audio, defaults to false
   */
  diarize?: boolean;
  /**
   * Milliseconds to wait before sending UtteranceEnd event (use with interim_results)
   */
  utteranceEndMs?: number;
  /**
   * Send SpeechStarted events when speech is detected, defaults to false
   */
  vadEvents?: boolean;

}

/**
 * AssemblyAI speech-to-text settings
 */
export interface AssemblyAiAsrSettings {
  /**
   * Audio sample rate in Hz (8000, 16000, 22050, 24000, 44100), defaults to 16000
   */
  sampleRate?: number;
  /**
   * Enable formatted transcripts with capitalization and punctuation (adds latency, not recommended for voice agents), defaults to false
   */
  formatTurns?: boolean;
  /**
   * Speech model to use: English-only or multilingual (supports English, Spanish, French, German, Italian, Portuguese), defaults to universal-streaming-english
   */
  speechModel?: 'universal-streaming-english' | 'universal-streaming-multilingual';
  /**
   * List of custom words or phrases to improve recognition accuracy
   */
  keytermsPrompt?: string[];
  /**
   * Voice activity detection confidence threshold (0.0 to 1.0) for classifying audio frames as silence, defaults to 0.4
   */
  vadThreshold?: number;
  /**
   * Confidence threshold (0.0 to 1.0) for determining end of turn, defaults to 0.4
   */
  endOfTurnConfidenceThreshold?: number;
  /**
   * Minimum silence in milliseconds required to detect end of turn when confident, defaults to 400
   */
  minEndOfTurnSilenceWhenConfident?: number;
  /**
   * Maximum silence in milliseconds allowed in a turn before triggering end of turn, defaults to 1280
   */
  maxTurnSilence?: number;
  /**
   * Time in seconds of inactivity before session is terminated (5-3600), no timeout if not set
   */
  inactivityTimeout?: number;

}

/**
 * Speechmatics speech-to-text settings
 */
export interface SpeechmaticsAsrSettings {
  /**
   * Language code for speech recognition (e.g., "en", "en-US", "es", "fr")
   */
  language?: string;
  /**
   * Audio input format for speech recognition, defaults to pcm_16000
   */
  audioFormat?: 'pcm_16000' | 'pcm_8000' | 'pcm_44100';
  /**
   * Transcription mode: "standard" for faster processing or "enhanced" for higher accuracy, defaults to standard
   */
  transcriptionMode?: 'standard' | 'enhanced';
  /**
   * Enable automatic punctuation in transcripts, defaults to true
   */
  enablePunctuation?: boolean;
  /**
   * Enable automatic formatting (numbers, dates, currency, etc.), defaults to true
   */
  enableFormatting?: boolean;
  /**
   * Custom vocabulary words or phrases to improve recognition accuracy
   */
  additionalVocab?: string[];
  /**
   * Enable speaker diarization to detect different speakers, defaults to false
   */
  enableDiarization?: boolean;
  /**
   * Maximum delay in seconds for transcription results (0-10), lower values reduce latency
   */
  maxDelay?: number;

}


// ============================================================================
// Session and Conversation Lifecycle
// ============================================================================

export interface StartConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for starting a new conversation
   */
  type: 'start_conversation';
  /**
   * Session ID in which to start the conversation
   */
  sessionId: string;
  /**
   * User ID initiating the conversation
   */
  userId: string;
  /**
   * Optional agent ID for the conversation
   */
  agentId?: string;
  /**
   * Stage ID to initiate the conversation at a specific stage
   */
  stageId: string;
  /**
   * IANA timezone identifier for this conversation (e.g. America/New_York, Europe/Warsaw). Overrides user profile and project timezone settings. Defaults to UTC when not provided by any source.
   */
  timezone?: string;
}

export interface StartConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for start conversation response
   */
  type: 'start_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully started
   */
  success: boolean;
  /**
   * Unique identifier for the created conversation
   */
  conversationId?: string;
  /**
   * Error message if conversation creation failed
   */
  error?: string;
}

export interface ResumeConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for resuming a conversation
   */
  type: 'resume_conversation';
  /**
   * Session ID in which to resume the conversation
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation to resume
   */
  conversationId: string;
}

export interface ResumeConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for resume conversation response
   */
  type: 'resume_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully resumed
   */
  success: boolean;
  /**
   * Unique identifier of the resumed conversation
   */
  conversationId?: string;
  /**
   * Error message if conversation resumption failed
   */
  error?: string;
}

export interface EndConversationRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for ending a conversation
   */
  type: 'end_conversation';
  /**
   * Session ID containing the conversation
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation to end
   */
  conversationId: string;
}

export interface EndConversationResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for end conversation response
   */
  type: 'end_conversation';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether conversation was successfully ended
   */
  success: boolean;
  /**
   * Error message if conversation termination failed
   */
  error?: string;
}

export interface ConversationEvent {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for conversation events
   */
  type: 'conversation_event';
  /**
   * Session ID containing the conversation
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Identifier of the input turn associated with the event, if applicable
   */
  inputTurnId?: string;
  /**
   * Identifier of the output turn associated with the event, if applicable
   */
  outputTurnId?: string;
  /**
   * Type of the conversation event
   */
  eventType:
    | 'message'
    | 'classification'
    | 'transformation'
    | 'action'
    | 'command'
    | 'tool_call'
    | 'conversation_start'
    | 'conversation_resume'
    | 'conversation_end'
    | 'conversation_aborted'
    | 'conversation_failed'
    | 'jump_to_stage'
    | 'moderation';
  /**
   * Data associated with the conversation event
   */
  eventData:
    | {
        role: 'user' | 'assistant';
        text: string;
        originalText: string;
        metadata?: Record<string, unknown>;
      }
    | {
        classifierId: string;
        input: string;
        actions: {
          classifierId: string;
          classifierName: string;
          actions: {
            name: string;
            parameters: {
              [k: string]: ParameterValue;
            };
          }[];
        }[];
        metadata?: Record<string, unknown>;
      }
    | {
        transformerId: string;
        input: string;
        appliedFields: string[];
        metadata?: Record<string, unknown>;
      }
    | {
        actionName: string;
        stageId: string;
        effects: Effect[];
        metadata?: Record<string, unknown>;
      }
    | {
        command: string;
        parameters?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        toolId: string;
        toolName: string;
        parameters: {
          [k: string]: ParameterValue;
        };
        success: boolean;
        result?: (
          | {
              contentType: 'text';
              text: string;
            }
          | {
              contentType: 'image';
              /**
               * Base64-encoded image data
               */
              data: string;
              /**
               * MIME type (e.g., image/png, image/jpeg)
               */
              mimeType: string;
              metadata?: {
                width?: number;
                height?: number;

              };
            }
          | {
              contentType: 'audio';
              /**
               * Base64-encoded audio data
               */
              data: string;
              /**
               * Audio format
               */
              format: 'pcm' | 'mp3' | 'wav' | 'opus';
              /**
               * MIME type (e.g., audio/pcm, audio/mpeg)
               */
              mimeType: string;
              metadata?: {
                sampleRate?: number;
                channels?: number;
                bitDepth?: number;

              };
            }
        )[];
        error?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        stageId: string;
        initialVariables?: {
          [k: string]: ParameterValue;
        };
        metadata?: Record<string, unknown>;
      }
    | {
        previousStatus:
          | 'initialized'
          | 'awaiting_user_input'
          | 'receiving_user_voice'
          | 'processing_user_input'
          | 'generating_response'
          | 'finished'
          | 'aborted'
          | 'failed';
        stageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason?: string;
        stageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        reason: string;
        stageId?: string;
        metadata?: Record<string, unknown>;
      }
    | {
        fromStageId: string;
        toStageId: string;
        metadata?: Record<string, unknown>;
      }
    | {
        input: string;
        flagged: boolean;
        blockingCategories: string[];
        detectedCategories: string[];
        durationMs: number;
        metadata?: Record<string, unknown>;
      };
}


// ============================================================================
// User Input (Voice and Text)
// ============================================================================

export interface StartUserVoiceInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for starting user voice input
   */
  type: 'start_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
}

export interface StartUserVoiceInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for start user voice input response
   */
  type: 'start_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice input was successfully started
   */
  success: boolean;
  /**
   * Error message if voice input start failed
   */
  error?: string;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId: string;
}

export interface SendUserVoiceChunkRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for sending user voice chunk
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
  /**
   * Sequential order of this chunk in the voice input sequence
   */
  ordinal: number;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId: string;
}

export interface SendUserVoiceChunkResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for send user voice chunk response
   */
  type: 'send_user_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice chunk was successfully received
   */
  success: boolean;
  /**
   * Error message if voice chunk processing failed
   */
  error?: string;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId: string;
}

export interface EndUserVoiceInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for ending user voice input
   */
  type: 'end_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId: string;
}

export interface EndUserVoiceInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for end user voice input response
   */
  type: 'end_user_voice_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether voice input was successfully ended
   */
  success: boolean;
  /**
   * Error message if voice input ending failed
   */
  error?: string;
  /**
   * Unique identifier for the input turn
   */
  inputTurnId: string;
}

export interface SendUserTextInputRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for sending user text input
   */
  type: 'send_user_text_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Text content from the user
   */
  text: string;
}

export interface SendUserTextInputResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for send user text input response
   */
  type: 'send_user_text_input';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether text input was successfully received
   */
  success: boolean;
  /**
   * Error message if text input processing failed
   */
  error?: string;
  /**
   * Unique identifier for the input turn, can be used to correlate with voice input if applicable
   */
  inputTurnId: string;
}

export interface UserTranscribedChunk {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for user text chunk
   */
  type: 'user_transcribed_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for the input turn this chunk belongs to
   */
  inputTurnId: string;
  /**
   * Unique identifier for this text chunk
   */
  chunkId: string;
  /**
   * Chunk of transcribed text input from the user
   */
  chunkText: string;
  /**
   * Sequential order of this chunk in the transcription sequence
   */
  ordinal: number;
  /**
   * Whether this is the final version of the chunk of text input
   */
  isFinal: boolean;
}


// ============================================================================
// AI Response (Voice Output)
// ============================================================================

export interface StartAiGenerationOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for starting AI voice output
   */
  type: 'start_ai_generation_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  outputTurnId: string;
  /**
   * Whether the AI response will include voice output
   */
  expectVoice: boolean;
}

export interface SendAiVoiceChunk {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for sending AI voice chunk
   */
  type: 'send_ai_voice_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  outputTurnId: string;
  /**
   * Base64-encoded audio chunk data
   */
  audioData: string;
  /**
   * Audio format of the chunk data
   */
  audioFormat:
    | 'mp3'
    | 'opus'
    | 'aac'
    | 'flac'
    | 'wav'
    | 'pcm_8000'
    | 'pcm_16000'
    | 'pcm_22050'
    | 'pcm_24000'
    | 'pcm_44100'
    | 'pcm_48000'
    | 'mulaw'
    | 'alaw'
    | 'linear16';
  /**
   * Unique identifier for this specific audio chunk
   */
  chunkId: string;
  /**
   * Sequential order of this chunk in the voice output sequence
   */
  ordinal: number;
  /**
   * Whether this is the final chunk in the voice output sequence
   */
  isFinal: boolean;
  /**
   * Sample rate of the audio chunk (e.g., 24000)
   */
  sampleRate?: number;
  /**
   * Bit rate of the audio chunk in bits per second (e.g., 64000)
   */
  bitRate?: number;
}

export interface EndAiGenerationOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for ending AI voice output
   */
  type: 'end_ai_generation_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this voice output sequence for correlation
   */
  outputTurnId: string;
  /**
   * The full text that was converted to speech, if available
   */
  fullText: string;
}

export interface AiTranscribedChunk {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for AI transcribed text chunk
   */
  type: 'ai_transcribed_chunk';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for the output turn this chunk belongs to
   */
  outputTurnId: string;
  /**
   * Unique identifier for this text chunk
   */
  chunkId: string;
  /**
   * Chunk of transcribed text output from the AI
   */
  chunkText: string;
  /**
   * Sequential order of this chunk in the transcription sequence
   */
  ordinal: number;
  /**
   * Whether this is the final chunk of text output
   */
  isFinal: boolean;
}

export interface SendAiAudioOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for sending AI-generated audio
   */
  type: 'send_ai_audio_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this output sequence for correlation
   */
  outputTurnId: string;
  /**
   * Base64-encoded audio data
   */
  audioData: string;
  /**
   * Audio format identifier
   */
  audioFormat: 'pcm' | 'mp3' | 'wav' | 'opus';
  /**
   * MIME type of the audio (e.g., audio/pcm, audio/mpeg)
   */
  mimeType: string;
  /**
   * Sequence number if multiple audio blocks in response
   */
  sequenceNumber: number;
  /**
   * Audio metadata
   */
  metadata?: {
    /**
     * Sample rate in Hz
     */
    sampleRate?: number;
    /**
     * Number of audio channels
     */
    channels?: number;
    /**
     * Bit depth per sample
     */
    bitDepth?: number;
  };
}

export interface SendAiImageOutput {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for sending AI-generated image
   */
  type: 'send_ai_image_output';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier for this output sequence for correlation
   */
  outputTurnId: string;
  /**
   * Base64-encoded image data
   */
  imageData: string;
  /**
   * MIME type of the image (e.g., image/png, image/jpeg)
   */
  mimeType: string;
  /**
   * Sequence number if multiple images in response
   */
  sequenceNumber: number;
}


// ============================================================================
// Commands (Stage Navigation, Variables, Actions)
// ============================================================================

export interface GoToStageRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for navigating to a stage
   */
  type: 'go_to_stage';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the target stage
   */
  stageId: string;
}

export interface GoToStageResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for go to stage response
   */
  type: 'go_to_stage';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether navigation to the stage was successful
   */
  success: boolean;
  /**
   * Error message if navigation failed
   */
  error?: string;
}

export interface SetVarRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for setting a variable
   */
  type: 'set_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
  /**
   * Name of the variable to set
   */
  variableName: string;
  variableValue: ParameterValue & {

  };
}

export interface SetVarResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for set variable response
   */
  type: 'set_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variable was successfully set
   */
  success: boolean;
  /**
   * Error message if setting the variable failed
   */
  error?: string;
}

export interface GetVarRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for getting a variable
   */
  type: 'get_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
  /**
   * Name of the variable to retrieve
   */
  variableName: string;
}

export interface GetVarResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for get variable response
   */
  type: 'get_var';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variable was successfully retrieved
   */
  success: boolean;
  /**
   * Name of the retrieved variable
   */
  variableName: string;
  /**
   * Value of the variable (undefined if not found)
   */
  variableValue?:
    | string
    | number
    | boolean
    | {

      }
    | string[]
    | number[]
    | boolean[]
    | {

      }[]
    | ImageParameterValue
    | AudioParameterValue;
  /**
   * Error message if retrieving the variable failed
   */
  error?: string;
}

export interface GetAllVarsRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for getting all variables
   */
  type: 'get_all_vars';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the stage
   */
  stageId: string;
}

export interface GetAllVarsResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for get all variables response
   */
  type: 'get_all_vars';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the variables were successfully retrieved
   */
  success: boolean;
  /**
   * Map of variable names to their values
   */
  variables: {
    [k: string]: ParameterValue;
  };
  /**
   * Error message if retrieving variables failed
   */
  error?: string;
}

export interface RunActionRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for running an action
   */
  type: 'run_action';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Name of the global action to execute
   */
  actionName: string;
  /**
   * Map of parameter names to their values
   */
  parameters: {
    [k: string]: ParameterValue;
  };
}

export interface RunActionResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for run action response
   */
  type: 'run_action';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the action was successfully executed
   */
  success: boolean;
  /**
   * Result returned by the action as array of multi-modal content blocks (text, image, or audio)
   */
  result?: (
    | {
        contentType: 'text';
        text: string;
      }
    | {
        contentType: 'image';
        /**
         * Base64-encoded image data
         */
        data: string;
        /**
         * MIME type (e.g., image/png, image/jpeg)
         */
        mimeType: string;
        metadata?: {
          width?: number;
          height?: number;

        };
      }
    | {
        contentType: 'audio';
        /**
         * Base64-encoded audio data
         */
        data: string;
        /**
         * Audio format
         */
        format: 'pcm' | 'mp3' | 'wav' | 'opus';
        /**
         * MIME type (e.g., audio/pcm, audio/mpeg)
         */
        mimeType: string;
        metadata?: {
          sampleRate?: number;
          channels?: number;
          bitDepth?: number;

        };
      }
  )[];
  /**
   * Error message if action execution failed
   */
  error?: string;
}

export interface CallToolRequest {
  /**
   * Unique identifier for request correlation and tracking
   */
  requestId: string;
  /**
   * Message type for calling a tool
   */
  type: 'call_tool';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Unique identifier of the conversation
   */
  conversationId: string;
  /**
   * Unique identifier of the tool to execute
   */
  toolId: string;
  /**
   * Map of parameter names to their values
   */
  parameters: {
    [k: string]: ParameterValue;
  };
}

export interface CallToolResponse {
  /**
   * Optional request ID for correlating responses with requests
   */
  requestId?: string;
  /**
   * Message type for call tool response
   */
  type: 'call_tool';
  /**
   * Unique identifier for the session
   */
  sessionId: string;
  /**
   * Whether the tool was successfully executed
   */
  success: boolean;
  /**
   * Result returned by the tool execution as array of multi-modal content blocks (text, image, or audio)
   */
  result?: (
    | {
        contentType: 'text';
        text: string;
      }
    | {
        contentType: 'image';
        /**
         * Base64-encoded image data
         */
        data: string;
        /**
         * MIME type (e.g., image/png, image/jpeg)
         */
        mimeType: string;
        metadata?: {
          width?: number;
          height?: number;

        };
      }
    | {
        contentType: 'audio';
        /**
         * Base64-encoded audio data
         */
        data: string;
        /**
         * Audio format
         */
        format: 'pcm' | 'mp3' | 'wav' | 'opus';
        /**
         * MIME type (e.g., audio/pcm, audio/mpeg)
         */
        mimeType: string;
        metadata?: {
          sampleRate?: number;
          channels?: number;
          bitDepth?: number;

        };
      }
  )[];
  /**
   * Error message if tool execution failed
   */
  error?: string;
}

